### ISSUE TITLE
Question about test91 example

### ISSUE THREAD

**Issue by zxkjack123** [fispact/pypact#33]
Like this `pypact` package, very helpful for FISPACT users.
I followed the instruction on "README" to try it with the `test91.out` convert example.
A new `test91_new.json` was created by the command ```fispactconverter.py test91.out test91_new.json```, but it has different content with the `test91.json` provided in `reference`:
```
drwxr-xr-x  2 gw gw 4.0K 1月  21 10:16 ./
drwxrwxr-x 17 gw gw 4.0K 1月  21 10:08 ../
-rw-r--r--  1 gw gw 103K 1月  21 10:08 test91.json
-rw-r--r--  1 gw gw 152K 1月  21 10:16 test91_new.json
-rw-r--r--  1 gw gw 192K 1月  21 10:08 test91.out
```
The new generated file `test91_new.json` has 152K, 4491 lines. But the reference one has 103K, 3009 lines.
Is my installation failed? Or the reference `test91.json` need to update?

**Comment by thomasms** [comment]
You can trust your installation, the README is outdated. I do intend to improve the documentation at some point but currently short on time. We added some extra fields since that README was written, hence the file size is now bigger. Certain additional properties such as the number of atoms, number of fissions, and the gamma spectrum were added in recent versions of pypact. 

I have ran the same example as you and indeed get the same result.
![image](https://user-images.githubusercontent.com/8820266/105320712-cadc0080-5bc6-11eb-9e20-40708079fe5b.png)

**Comment by zxkjack123** [comment]
@thomasms Thanks a lot. 
As the question got answered, close this issue.
